name: helping_hands_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^14.2.0
  provider: ^6.1.2
  
  # Supabase & Database
  supabase_flutter: ^2.8.0
  
  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.9.4
  
  # HTTP & Networking
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  
  # Location & Maps
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  
  # Local Storage
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  
  # File & Media
  image_picker: ^1.1.2
  file_selector: ^1.0.3
  
  # Notifications
  flutter_local_notifications: ^17.2.1+2
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  url_launcher: ^6.3.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
  #   - family: Manjari
  #     fonts:
  #       - asset: assets/fonts/Manjari-Regular.ttf 